package com.example.pavelkovachev.recipes.network;

public class JsonConstants {

    public static final String CATEGORIES_KEY = "categories";
    public static final String MEALS_KEY = "meals";
    public static final String NAME_KEY = "strMeal";
    public static final String ID_KEY = "idMeal";
    public static final String IMAGE_KEY = "strMealThumb";
    public static final String CUISINE_KEY = "strArea";
    public static final String MEAL_TYPE_KEY = "strCategory";
    public static final String MEAL_TYPE_DESCRIPTION_KEY = "strCategoryDescription";
    public static final String INSTRUCTIONS_KEY = "strInstructions";
    public static final String INGREDIENT_1_KEY = "strIngredient1";
    public static final String INGREDIENT_2_KEY = "strIngredient2";
    public static final String INGREDIENT_3_KEY = "strIngredient3";
    public static final String INGREDIENT_4_KEY = "strIngredient4";
    public static final String INGREDIENT_5_KEY = "strIngredient5";
    public static final String INGREDIENT_6_KEY = "strIngredient6";
    public static final String INGREDIENT_7_KEY = "strIngredient7";
    public static final String INGREDIENT_8_KEY = "strIngredient8";
    public static final String INGREDIENT_9_KEY = "strIngredient9";
    public static final String INGREDIENT_10_KEY = "strIngredient10";
    public static final String INGREDIENT_11_KEY = "strIngredient11";
    public static final String INGREDIENT_12_KEY = "strIngredient12";
    public static final String INGREDIENT_13_KEY = "strIngredient13";
    public static final String INGREDIENT_14_KEY = "strIngredient14";
    public static final String INGREDIENT_15_KEY = "strIngredient15";
    public static final String INGREDIENT_16_KEY = "strIngredient16";
    public static final String INGREDIENT_17_KEY = "strIngredient17";
    public static final String INGREDIENT_18_KEY = "strIngredient18";
    public static final String INGREDIENT_19_KEY = "strIngredient19";
    public static final String INGREDIENT_20_KEY = "strIngredient20";
    public static final String MEASURE_1_KEY = "strMeasure1";
    public static final String MEASURE_2_KEY = "strMeasure2";
    public static final String MEASURE_3_KEY = "strMeasure3";
    public static final String MEASURE_4_KEY = "strMeasure4";
    public static final String MEASURE_5_KEY = "strMeasure5";
    public static final String MEASURE_6_KEY = "strMeasure6";
    public static final String MEASURE_7_KEY = "strMeasure7";
    public static final String MEASURE_8_KEY = "strMeasure8";
    public static final String MEASURE_9_KEY = "strMeasure9";
    public static final String MEASURE_10_KEY = "strMeasure10";
    public static final String MEASURE_11_KEY = "strMeasure11";
    public static final String MEASURE_12_KEY = "strMeasure12";
    public static final String MEASURE_13_KEY = "strMeasure13";
    public static final String MEASURE_14_KEY = "strMeasure14";
    public static final String MEASURE_15_KEY = "strMeasure15";
    public static final String MEASURE_16_KEY = "strMeasure16";
    public static final String MEASURE_17_KEY = "strMeasure17";
    public static final String MEASURE_18_KEY = "strMeasure18";
    public static final String MEASURE_19_KEY = "strMeasure19";
    public static final String MEASURE_20_KEY = "strMeasure20";
}
